### PR TITLE
Add option to filter nagios host list by monitored site

### PR DESCRIPTION
**Pull request by stevie-**
If we use omd-host-crud create HOSTNAME no additonal parameters are set, so we should not rely on it, when we read information of a host

### CODE REVIEW

**Comment by tskirvin** [comment]
Can you explain a bit more what this commit does?

**Comment by stevie-** [comment]
Sorry I mixed a lot commits o.0

But main change is to `omd-nagios-hostlist`.
I added an option to specify a site filter. This filters out hosts which are monitored on a specific site.
Without this filter, all hosts are listed as usual.

**Comment by epleterte** [comment]
Other things added by this commit seems to be conditional printing of 'alias', 'role', 'instance' based on whether these properties are set or not, and some removal of trailing whitespace and empty lines.

**Comment by stevie-** [comment]
Yes, minor stuff which should be non breaking

**Review by tskirvin — APPROVED** [review]
adds filter-by-site; omd-host-crud read works better when not all tags exist

**Comment by stevie-** [comment]
thanks

**Pull request merged**
